sonar.projectKey=badinventoryreact
sonar.projectName=BadInventoryReact
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src/tests

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,dist/**

sonar.coverage.exclusions=src/models/**

sonar.host.url=http://localhost:9000
sonar.token=squ_381a858374e8a9e7214319e20e6c386cb74d6b1b