name: SonarQube Scan

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=my-project
            -Dsonar.sources=.
            -Dsonar.host.url=https://49b2-186-154-38-51.ngrok-free.app